### PR TITLE
Save and restore context state on reboots, improve dbus errors and add more logging 

### PR DESCRIPTION
**Pull request by FakeShell**
Would be nice to get a review also from @JZX100II as he was involved in getting some of this work done

### CODE REVIEW

**Review by JZX100II — APPROVED** [review]
The subprocess.check_output(cmd) can throw exceptions and cause the program to terminate unexpectedly. In order to handle this situation, we can put try/except blocks around these lines to catch potential exceptions thrown by subprocess.check_output(cmd).

**Comment by FakeShell** [comment]
i think it should be OK now, while i was at it, i also fixed a bug where if SimManager doesn't provide the prop for sim, then we can fallback to NetworkRegistration interface

**Review by JZX100II — APPROVED** [review]
Great work on this code. The Addition of exception handling for subprocess.check_output(cmd) ensures the program won't terminate unexpectedly if a command fails.

**Comment by FakeShell** [comment]
merging this into staging so that it can be tested easier.

**Pull request merged**
